# Generated by Django 2.0.2 on 2018-04-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('author', models.CharField(max_length=255)),
                ('last_used', models.DateTimeField()),
            ],
        ),
    ]
