# Generated by Django 2.0.2 on 2018-04-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('elapsed', models.DurationField()),
            ],
        ),
    ]
