# Generated by Django 2.0.2 on 2018-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(default='None', max_length=255)),
                ('due_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('all_day', models.NullBooleanField()),
            ],
        ),
    ]
